export let cats = [
	['Seneca', 'Calico'],
	['Freya', 'Tabby'],
	['Okra', 'Tortie'],
	['Nico', 'Black'],
	['rOka', 'Mixed Up'],
	['Manon', 'Internet Cat'],
	['Samsek', 'Internet Cat'],
	['Lulu', 'Internet Cat'],
	['Chessica', 'Stray Cat'],
	['Voodoo', 'Stray Cat'],
	['Gilmak', 'Internet Cat'],
	['Chuchu', 'Internet Cat'],
	['Tuskie', 'Stray Cat'],
	['Mia', 'Stray Cat'],
	['Tilia', 'Stray Cat'],
	['TT', 'Internet Cat'],
	['CoCo', 'Internet Cat'],
	['Mu', 'Stray Cat'],
	['Todo', 'Internet Cat'],
	['Dodo', 'Internet Cat'],
	['Reagi', 'Stray Cat'],
	['Shulgin', 'Stray Cat'],
	['Hoffman', 'Stray Cat'],
	['DD', 'Internet Cat'],
	['Ferg', 'Internet Cat'],
	['Lola', 'Good Dog'],
	['Olie', 'Good Dog'],
];
